routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/test', function () {
    return view('profile.index');
});

//route laravel-excel
Route::get('user/export', 'UserController@export');
Route::get('categories/export', 'categoryController@export');
Route::get('role/export', 'RoleController@export');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/blogAdmin', 'blogAdminController@index');
Route::get('/blog', 'blogUserController@index');

Route::resource('profile', 'ProfileController');

Route::resource('categories','categoryController');

Route::post('comment/post','CommentController@store');
Route::resource('user', 'UserController');
Route::resource('role', 'RoleController');
Route::resource('categories','categoryController');  

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $table = "categories";

    protected $fillable = ['title','content','parentId'];
    //
	
	//many to many relationship post
	public function posts()
    {
        return $this->belongsToMany('App\Post', 'posts_categories', 'categoryId', 'postId');
    }
}

app/Http/Controllers/categoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Exports\UsersExport;
use Maatwebsite\Excel\Facades\Excel;
use App\Category;
use Carbon\Carbon;

class categoryController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    
	public function __construct()
    {
        $this->middleware('auth');
    }
	
	public function export() 
    {
        return Excel::download(new CategoryExport, 'category.xlsx');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $category = Category::all();
        return view('categories.index',compact('category'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'title' => 'required',
            'content'   => 'required'
        ]);
        $nows=Carbon::now()->toDateString();

      //  $questions = DB::table('pertanyaan')->insert([
    //       "judul" => $request["judul"],
    //       "isi" => $request["isi"],
    //       "tanggal_dibuat" => $nows,
    //      "tanggal_diperbaharui" => $nows
    //        ]);

        $category = Category::create([
            "title" => $request["title"],
            "content" => $request["content"],
            "parentId" => 1
        ]);        
        return redirect('/categories')->with('success','Save Data Successfull');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $category = Category::find($id);
        return view('categories.show',compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $category = Category::find($id);
        return view('categories.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $nows=Carbon::now()->toDateString();
        // $questions = DB::table('pertanyaan')->where('id',$id)->update([
        //         "judul" => $request["judul"],
        //         "isi" => $request["isi"],
        //         "tanggal_diperbaharui" => $nows
        //     ]);
        $category = Category::where('id',$id)->update([
                "title" => $request["title"],
                "content" => $request["content"]
        ]);
        return redirect('/categories')->with('success','Update Data Successfull');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Category::destroy($id);
        return redirect('/categories')->with('success','Delete Data Successfull');
    }
}

resources/views/categories/create.blade.php
@extends('admin.app')


@section('content')
          <div class="ml-3 mt-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">New Category</h3>
              </div>
                            <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{ route('categories.store') }}" method="POST">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title"  name="title" value="{{ old('title' , '') }}" placeholder="Insert Title">
                    @error('title')
              <div class="alert alert-danger"> {{ $messages }}</div>
              @enderror
                  </div>
                  <div class="form-group">
                    <label for="content">Content</label>
                    <input type="text" class="form-control" id="content" name="content" value="{{ old('content', '') }}" placeholder="Insert Content">
                    @error('content')
              <div class="alert alert-danger"> {{ $messages }}</div>
              @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Save</button>
                </div>
              </form>
            </div>
          </div>
@endsection

resources/views/categories/edit.blade.php
@extends('admin.app')


@section('content')
          <div class="ml-3 mt-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Category </h3>
              </div>
                            <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{ route('categories.update',['category'=> $category->id]) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="Title">Title</label>
                    <input type="text" class="form-control" id="title"  name="title" value="{{ old('title' , $category->title) }}" placeholder="Insert Title">
                    @error('judul')
              <div class="alert alert-danger"> {{ $messages }}</div>
              @enderror
                  </div>
                  <div class="form-group">
                    <label for="Content">Content</label>
                    <input type="text" class="form-control" id="content" name="content" value="{{ old('content', $category->content) }}" placeholder="Insert Content">
                    
                    @error('isi')
              <div class="alert alert-danger"> {{ $messages }}</div>
              @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Save</button>
                </div>
              </form>
            </div>
          </div>
@endsection

resources/views/categories/index.blade.php
@extends('admin.app')


@section('content')
<div class="card">
      <div class="card-header">
        <h3 class="card-title">Categories</h3>
      </div>
	   <div class="panel-heading ml-4 mb-2">
                <a href="/categories/export" title="Input data"><button name="input" class="btn btn-primary">Download Excel</button></a>
        </div>
      <!-- /.card-header -->
      <div class="card-body">
        @if(session('success'))
          <div class="alert alert-success"> {{ session('success') }}</div>
        @endif
        <a class="btn btn-primary mb-2" href="{{ route('categories.create') }}"> Create New Category</a>
        <table id="dataPertanyaan" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>No</th>
            <th>Title</th>
            <th>Content</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody>
            @forelse($category as $key => $categ)
          <tr>
            <td>{{ $key +1 }}</td>
            <td>{{ $categ->title ?? '' }}</td>
            <td>{{ $categ->content ?? ''}}</td>
            <td style="display: flex;">
                <a href="{{ route('categories.show', ['category'=> $categ->id]) }}" class="btn btn-info btn-sm">Show</a> <a href="{{ route('categories.edit', ['category'=> $categ->id]) }}" class="btn btn-default btn-sm">Edit</a> <form action="{{ route('categories.destroy', ['category'=> $categ->id]) }}" method="POST">
                  @csrf
                  @method('DELETE')
                  <input type="submit" value="delete" class="btn btn-danger btn-sm">
                </form>
            </td>
          </tr>
          @empty
          <tr>
            <td colspan="7" align="center">No Data</td>
          </tr>
            @endforelse
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
@endsection

resources/views/categories/show.blade.php
@extends('admin.app')

@section('content')
          <div class="ml-3 mt-3">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Category {{$category->id}}</h3>
              </div>
                            <!-- /.card-header -->
              <!-- form start -->
               <div class="card-body">
        <a class="btn btn-primary mb-2" href="{{ route('categories.index') }}"> Back</a>
        <table id="detailPertanyaan" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>Column</th>
            <th>Value</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>ID</td>
            <td>{{ $category->id ?? '' }}</td>
          </tr>
          <tr>
            <td>Title</td>
            <td>{{ $category->title ?? '' }}</td>
          </tr>
          <tr>
            <td>Content</td>
            <td>{{ $category->content ?? '' }}</td>
          </tr>
          <tr>
            <td>Create At</td>
            <td>{{ $category->created_at ?? '' }}</td>
          </tr>
          <tr>
            <td>Update At</td>
            <td>{{ $category->updated_at ?? '' }}</td>
          </tr>
          </tbody>
        </table>
      </div>
              </div>
          </div>
@endsection